# Generated by Django 5.1.7 on 2025-03-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management_app_v1', '0003_alter_event_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='event_type_id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='organizer_id',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='event',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='user_id',
        ),
    ]
