# Generated by Django 5.1.7 on 2025-04-04 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_up_v1', '0002_remove_event_notifications_remove_event_reviewer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='event_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='event_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event_up_v1.event'),
            preserve_default=False,
        ),
    ]
