# Generated by Django 5.1.7 on 2025-04-08 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_up_v1', '0004_remove_ticket_user_id_invoice_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='event_up_v1.discount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='final_amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ticket_count',
            field=models.IntegerField(blank=True),
        ),
    ]
