# Generated by Django 5.1.7 on 2025-04-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_up_v1', '0006_alter_invoice_amount_alter_invoice_final_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
