# Generated by Django 5.1.7 on 2025-04-09 02:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_up_v1', '0008_alter_ticket_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='qr_codes'),
        ),
    ]
