# Generated by Django 5.1.7 on 2025-04-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_up_v1', '0010_alter_review_rating_alter_review_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='event_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
