# Generated by Django 5.1.7 on 2025-04-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_up_v1', '0011_remove_notification_event_id_notification_sent_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['sent_at']},
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
