# Generated by Django 5.1.7 on 2025-04-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_up_v1', '0012_alter_notification_options_delete_chatmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventType',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_type_id',
            new_name='category_id',
        ),
    ]
