# Generated by Django 5.1.7 on 2025-05-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_up_v1', '0013_rename_eventtype_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
