# Generated by Django 5.1.7 on 2025-05-06 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_up_v1', '0014_event_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='event_up_v1.event'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='invoice_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='event_up_v1.invoice'),
        ),
        migrations.CreateModel(
            name='FavoriteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_up_v1.event')),
                ('participant_id', models.ForeignKey(limit_choices_to={'participant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['participant_id', 'event_id'], name='event_up_v1_partici_0a57dc_idx')],
                'unique_together': {('participant_id', 'event_id')},
            },
        ),
    ]
