# Generated by Django 5.1.7 on 2025-05-06 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_up_v1', '0015_alter_invoice_event_id_alter_ticket_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='feature_vector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favoriteevent',
            name='participant_id',
            field=models.ForeignKey(limit_choices_to={'role': 'participant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='participant_id',
            field=models.ForeignKey(limit_choices_to={'role': 'participant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_up_v1.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
    ]
