# Generated by Django 5.1.7 on 2025-05-11 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_up_v1', '0017_reviewresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewresponse',
            name='review_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='event_up_v1.review'),
        ),
    ]
