# Generated by Django 5.1.7 on 2025-05-11 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_up_v1', '0018_alter_reviewresponse_review_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewresponse',
            unique_together=set(),
        ),
    ]
