# Generated by Django 5.1.7 on 2025-05-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_up_v1', '0021_alter_reviewresponse_review_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['active'], name='event_up_v1_active_87cb23_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['views'], name='event_up_v1_views_0c6729_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category_id'], name='event_up_v1_categor_e50624_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer_id'], name='event_up_v1_organiz_9ddd14_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['payment_status'], name='event_up_v1_payment_008c03_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user_id'], name='event_up_v1_user_id_1315c3_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['event_id'], name='event_up_v1_event_i_e12101_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['event_id'], name='event_up_v1_event_i_41dafb_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['active'], name='event_up_v1_active_828a42_idx'),
        ),
    ]
