# Generated by Django 5.1.7 on 2025-05-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_up_v1', '0022_event_event_up_v1_active_87cb23_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['invoice_id'], name='event_up_v1_invoice_70da5a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='event_up_v1_status_29aa54_idx'),
        ),
    ]
