# Generated by Django 5.1.7 on 2025-05-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_up_v1', '0023_ticket_event_up_v1_invoice_70da5a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
