# Generated by Django 5.1.7 on 2025-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_up_v1', '0025_alter_userpreference_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
