# Generated by Django 5.1.7 on 2025-05-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_up_v1', '0027_user_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_sold',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
