# Generated by Django 5.1.7 on 2025-06-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_up_v1', '0028_event_ticket_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
